

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: stockerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
    
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: stocker-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=dpg-d4e3ub6mcj7s73celhlg-a.oregon-postgres.render.com;Port=5432;Database=stockerdb;Username=admin;Password=01PvijuhRDqmfni80wa89uRby3S3AuQF;SSL Mode=Require;Trust Server Certificate=true
    ports:
      - "5052:8080"
    depends_on:
       - postgres
  
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: stocker-client
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  postgres_data: